project:
  type: website
  output-dir: docs

website:
  favicon: figs/crow_s.png
  title: "RAVENSNEST"
  google-analytics: "G-XJSP4R93HW"
  open-graph: true
  site-url: https://yunyi-ru.github.io/quarto-blog/
  site-path: "/"
  body-footer: |
    Â© 2024-2025 RavensNest.
  navbar:
    left:
    - text: Projects
      href: project.qmd
    - text: Blog
      href: blog.qmd
    right:
    - text: About
      href: aboutme.qmd
    - icon: github
      href: https://github.com/yunyi-ru

format:
  html:
    theme:
      - morph
      - custom.scss

editor: visual

callout-appearance: simple
