project:
  type: website
  output-dir: docs

website:
  favicon: figs/crow_s.png
  title: "Raven's Nest"
  google-analytics: "G-XJSP4R93HW"
  image: figs/preview.png
  open-graph: true
  description: "Raven's Nest, a personal blog"
  site-url: https://yyraven.github.io/quarto-blog/
  site-path: "/"
  body-footer: |
    <center>Â© 2024-2025 RavensNest.</center>
  navbar:
    left:
    - text: Projects
      href: project.qmd
    - text: Blog
      href: blog.qmd
    - text: Life
      href: life.qmd
    - text: Archive
      href: archive.qmd
    right:
    - text: About
      href: aboutme.qmd
    - text: RSS
      href: index.xml
    - icon: github
      href: https://github.com/yyraven

format:
  html:
    theme:
        - morph
        - custom.scss

editor: visual

callout-appearance: simple
